### ISSUE TITLE
Your Github profile and projects look amazing. 🚀 

### ISSUE THREAD

**Issue by NayakPenguin** [sumit2011/sumit2011.github.io#1]
Your Github profile and projects look amazing. 🚀

Can you please star mark my project : https://github.com/Nayaker/AlgoListed

Sorry for creating an issue :)

**Comment by sumit2011** [comment]
yours too...

and you also mark mine :|

**Comment by NayakPenguin** [comment]
Which one?

**Comment by sumit2011** [comment]
leave it.

**Comment by NayakPenguin** [comment]
Thanks for staring mine ❤️
